#!/bin/bash
echo "Which file to chmod?"
read file_name
chmod u+x $file_name
echo "what is your commig message?"
read Message
git add .
git commit -m "${Message}"
git push origin master
echo "DONE: git push ${Message} commit."
git status
